project 'VK.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VK' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VK
pod 'Alamofire'
  target 'VKTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VKUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
